version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
  mysql:
    container_name: database-module-mysql
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=pokemons
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: